from typing import Protocol

class ReportMetricsRepository(Protocol):
    async def count_total_requests(self) -> int: ...
    async def count_completed_success(self) -> int: ...
    async def count_outbox_pending(self) -> int: ...

class WorkerProbe(Protocol):
    # active, reserved, scheduled
    async def get_counts(self) -> tuple[int, int, int]: ...

class BrokerProbe(Protocol):
    async def count_queued(self) -> int: ...