from typing import Protocol, Sequence
from app.domain.entities.outbox_event import OutboxEventEntity


class OutboxRepository(Protocol):
    async def add(self, event: OutboxEventEntity) -> OutboxEventEntity: ...
    async def list_pending(self, limit: int = 100) -> Sequence[OutboxEventEntity]: ...
    async def mark_dispatched(self, event_id: int) -> None: ...
    async def mark_failed(self, event_id: int, error: str) -> None: ...


