from typing import Protocol, Optional
from app.domain.entities.report_request import ReportRequestEntity


class ReportRepository(Protocol):
    async def add(self, report: ReportRequestEntity) -> ReportRequestEntity: ...

    async def get(self, report_id: int) -> Optional[ReportRequestEntity]: ...
    async def set_job_id(self, report_id: int, job_id: str) -> None: ...
    async def set_result(self, report_id: int, result_path: str) -> None: ...

    async def set_error(self, report_id: int, error_message: str) -> None: ...


