version: "3.9"

services:
  web:
    container_name: web
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - mysql
      - redis

  worker:
    container_name: worker
    build: .
    command: celery -A app.celery_app.celery_app worker --loglevel=INFO -E
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - web
      - redis

  beat:
    container_name: beat
    build: .
    command: celery -A app.celery_app.celery_app beat --loglevel=INFO
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - worker
      - redis

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=async_outbox
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


